[features]
seeds = false
skip-lint = false
[programs.localnet]
v4_spling = "fvHdsgDm2dk6Wo8sjYiDu6EALS9bLehLwXSjsPPwMjZ"

[programs.devnet]
v4_spling = "fvHdsgDm2dk6Wo8sjYiDu6EALS9bLehLwXSjsPPwMjZ"

[programs.mainnet]
v4_spling = "fvHdsgDm2dk6Wo8sjYiDu6EALS9bLehLwXSjsPPwMjZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/Users/nielsoskam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
